### PR TITLE
add Munich chapter

### PR DESCRIPTION
**Pull request by cko**

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
Thanks for this @cko, we'll update this soon. Do you mind adding a PR to https://github.com/papers-we-love/papers-we-love as well, just like https://github.com/papers-we-love/papers-we-love/pull/253 for example?

**Comment by ifesdjeen** [comment]
Done: https://github.com/papers-we-love/papers-we-love/pull/262#issuecomment-69321659

**Comment by DarrenN** [comment]
:+1:

**Comment by ifesdjeen** [comment]
not sure if it worked, still not present on the website itself

**Comment by zeeshanlakhani** [comment]
@ifesdjeen we just gotta build it. will do this evening.

**Comment by ifesdjeen** [comment]
Thanks! I thought maybe branch was wrong or something :) 

:fireworks:

**Comment by DarrenN** [comment]
Deployed: http://paperswelove.org/

Also added Munich's 1/27 meetup to the listing.

**Comment by ifesdjeen** [comment]
:+1: thank you!

**Pull request merged**
