### PR TITLE
Add saint-petersburg chapter

### PR DESCRIPTION
**Pull request by Termina1**
Also, we don't have a meetup.com profile, is this mandatory?

### CODE REVIEW

**Comment by DarrenN** [comment]
@Termina1 it isn't mandatory, but we won't be able to include you in the generated list of meetups we post on the site http://paperswelove.org/2017/news/february-meetups/

**Comment by andreypopp** [comment]
@DarrenN that's unfortunate... is there a way to fix the script which generates a list to include timepad based meetup pages? I can contribute.

**Comment by zeeshanlakhani** [comment]
@andreypopp It is something we're still working on. @DarrenN will have more updates as we make those changes. Also, do you mind resolving the conflicts here, and we'll merge this in to have the chapter on the site? Thanks.

**Comment by zeeshanlakhani** [comment]
@andreypopp make sure you pull the latest changes and rebase accordingly.

**Comment by Termina1** [comment]
@zeeshanlakhani done

**Pull request merged**
