### PR TITLE
add Kyiv chapter

### PR DESCRIPTION
**Pull request by liesnikov**
both to data/chapters.json and erb file

### CODE REVIEW

**Comment by DarrenN** [comment]
Hi @liesnikov - are you associated with https://github.com/papers-we-love/kyiv ?

**Comment by liesnikov** [comment]
Hi.
I take part in organization of the second meetup.
Should I ask any of the original organizers for a confirmation?

**Comment by joymax** [comment]
@DarrenN , confirming @liesnikov working on behalf of Kyiv PWL team

**Comment by liesnikov** [comment]
@DarrenN, does this suffice?

To avoid any misunderstanding, [@maxmaxmaxmax](https://twitter.com/maxmaxmaxmax) is @joymax twitter handle.

There is one more PR, referenced above, adding a link to the facebook page to papers-we-love repo.

**Comment by DarrenN** [comment]
@liesnikov this looks good to go. Just as a heads up, since you're using Facebook you won't show up in the listings more often than not. The onerous OAuth token system FB uses to wall off its content (you can't hold a token for more than a set period of time) means we often lose access FB data when generating the site. Just letting you know.

**Comment by liesnikov** [comment]
This shouldn't matter that much for us that much since we rely on the other channels for notification, but thanks for the notice anyway.

**Pull request merged**
