### PR TITLE
allspaw talk for tuesday. waiting on slides.

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
@DarrenN hope the embed link is proper. LMK if you need me to fix shit. Waiting on slides, will update accordingly.

### CODE REVIEW

**Comment by DarrenN** [comment]
@zeeshanlakhani this is all good to go, you just need to add slides right?

**Comment by zeeshanlakhani** [comment]
Yep. But we can update slides later if I don't get them in time. Oh, and switching the vid access. 

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love | paperswelove.org
twitter => @zeeshanlakhani

**Comment by DarrenN** [comment]
Okay, I'm gonna merge then?

**Comment by zeeshanlakhani** [comment]
If it builds right :), yep

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love | paperswelove.org
twitter => @zeeshanlakhani

**Comment by DarrenN** [comment]
Okay I'm gonna merge it, but be aware that it will get published automatically tonight around 12 - 2am

**Comment by zeeshanlakhani** [comment]
Cool. 

Zeeshan Lakhani
programmer | 
software engineer at @basho | 
org. member/founder of @papers_we_love | paperswelove.org
twitter => @zeeshanlakhani

**Pull request merged**
