### PR TITLE
add Chattanooga

### PR DESCRIPTION
**Pull request by NeilMenne**

### CODE REVIEW

**Comment by DarrenN** [comment]
Thanks @NeilMenne and congrats on your first meetup! 

To speed this up, make a duplicate of https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/partials/chapters/_boston.erb.markdown named `_chattanooga.erb.markdown` with your contact info. We can then merge everything in and rebuild the site.

**Comment by NeilMenne** [comment]
@DarrenN I see how things are wired together now. Thanks for the PR feedback!

**Comment by NeilMenne** [comment]
@DarrenN are there any other changes required before this is ready?

**Comment by DarrenN** [comment]
@NeilMenne - looks good!

**Pull request merged**
